/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let nav;
	let div1;
	let a0;
	let img;
	let img_src_value;
	let t0;
	let button;
	let span0;
	let t1;
	let span1;
	let t2;
	let span2;
	let t3;
	let div0;
	let ul;
	let li0;
	let a1;
	let t4;
	let t5;
	let li1;
	let a2;
	let t6;
	let t7;
	let li2;
	let a3;
	let t8;
	let t9;
	let li3;
	let a4;
	let t10;
	let t11;
	let li4;
	let a5;
	let span4;
	let span3;
	let t12;

	return {
		c() {
			nav = element("nav");
			div1 = element("div");
			a0 = element("a");
			img = element("img");
			t0 = space();
			button = element("button");
			span0 = element("span");
			t1 = space();
			span1 = element("span");
			t2 = space();
			span2 = element("span");
			t3 = space();
			div0 = element("div");
			ul = element("ul");
			li0 = element("li");
			a1 = element("a");
			t4 = text("Home");
			t5 = space();
			li1 = element("li");
			a2 = element("a");
			t6 = text("About");
			t7 = space();
			li2 = element("li");
			a3 = element("a");
			t8 = text("Portfolio");
			t9 = space();
			li3 = element("li");
			a4 = element("a");
			t10 = text("Blog");
			t11 = space();
			li4 = element("li");
			a5 = element("a");
			span4 = element("span");
			span3 = element("span");
			t12 = text("Get in touch");
			this.h();
		},
		l(nodes) {
			nav = claim_element(nodes, "NAV", { class: true });
			var nav_nodes = children(nav);
			div1 = claim_element(nav_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);
			a0 = claim_element(div1_nodes, "A", { class: true, href: true });
			var a0_nodes = children(a0);
			img = claim_element(a0_nodes, "IMG", { src: true, alt: true });
			a0_nodes.forEach(detach);
			t0 = claim_space(div1_nodes);

			button = claim_element(div1_nodes, "BUTTON", {
				class: true,
				type: true,
				"data-toggle": true,
				"data-target": true
			});

			var button_nodes = children(button);
			span0 = claim_element(button_nodes, "SPAN", { class: true });
			children(span0).forEach(detach);
			t1 = claim_space(button_nodes);
			span1 = claim_element(button_nodes, "SPAN", { class: true });
			children(span1).forEach(detach);
			t2 = claim_space(button_nodes);
			span2 = claim_element(button_nodes, "SPAN", { class: true });
			children(span2).forEach(detach);
			button_nodes.forEach(detach);
			t3 = claim_space(div1_nodes);
			div0 = claim_element(div1_nodes, "DIV", { class: true, id: true });
			var div0_nodes = children(div0);
			ul = claim_element(div0_nodes, "UL", { class: true });
			var ul_nodes = children(ul);
			li0 = claim_element(ul_nodes, "LI", { class: true });
			var li0_nodes = children(li0);
			a1 = claim_element(li0_nodes, "A", { class: true, href: true });
			var a1_nodes = children(a1);
			t4 = claim_text(a1_nodes, "Home");
			a1_nodes.forEach(detach);
			li0_nodes.forEach(detach);
			t5 = claim_space(ul_nodes);
			li1 = claim_element(ul_nodes, "LI", { class: true });
			var li1_nodes = children(li1);
			a2 = claim_element(li1_nodes, "A", { class: true, href: true });
			var a2_nodes = children(a2);
			t6 = claim_text(a2_nodes, "About");
			a2_nodes.forEach(detach);
			li1_nodes.forEach(detach);
			t7 = claim_space(ul_nodes);
			li2 = claim_element(ul_nodes, "LI", { class: true });
			var li2_nodes = children(li2);
			a3 = claim_element(li2_nodes, "A", { class: true, href: true });
			var a3_nodes = children(a3);
			t8 = claim_text(a3_nodes, "Portfolio");
			a3_nodes.forEach(detach);
			li2_nodes.forEach(detach);
			t9 = claim_space(ul_nodes);
			li3 = claim_element(ul_nodes, "LI", { class: true });
			var li3_nodes = children(li3);
			a4 = claim_element(li3_nodes, "A", { class: true, href: true });
			var a4_nodes = children(a4);
			t10 = claim_text(a4_nodes, "Blog");
			a4_nodes.forEach(detach);
			li3_nodes.forEach(detach);
			t11 = claim_space(ul_nodes);
			li4 = claim_element(ul_nodes, "LI", { class: true });
			var li4_nodes = children(li4);
			a5 = claim_element(li4_nodes, "A", { class: true, href: true });
			var a5_nodes = children(a5);
			span4 = claim_element(a5_nodes, "SPAN", { class: true });
			var span4_nodes = children(span4);
			span3 = claim_element(span4_nodes, "SPAN", { "data-text": true });
			var span3_nodes = children(span3);
			t12 = claim_text(span3_nodes, "Get in touch");
			span3_nodes.forEach(detach);
			span4_nodes.forEach(detach);
			a5_nodes.forEach(detach);
			li4_nodes.forEach(detach);
			ul_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			nav_nodes.forEach(detach);
			this.h();
		},
		h() {
			if (img.src !== (img_src_value = "assets/logo.png")) attr(img, "src", img_src_value);
			attr(img, "alt", "logo");
			attr(a0, "class", "navbar-brand svelte-10pddvj");
			attr(a0, "href", ".");
			attr(span0, "class", "icon-bar");
			attr(span1, "class", "icon-bar");
			attr(span2, "class", "icon-bar");
			attr(button, "class", "navbar-toggler collapsed");
			attr(button, "type", "button");
			attr(button, "data-toggle", "collapse");
			attr(button, "data-target", "#sitenavbar");
			attr(a1, "class", "nav-link svelte-10pddvj");
			attr(a1, "href", "/");
			attr(li0, "class", "nav-item svelte-10pddvj");
			attr(a2, "class", "nav-link svelte-10pddvj");
			attr(a2, "href", "/about");
			attr(li1, "class", "nav-item svelte-10pddvj");
			attr(a3, "class", "nav-link svelte-10pddvj");
			attr(a3, "href", "/portfolio");
			attr(li2, "class", "nav-item svelte-10pddvj");
			attr(a4, "class", "nav-link svelte-10pddvj");
			attr(a4, "href", "/blog");
			attr(li3, "class", "nav-item svelte-10pddvj");
			attr(span3, "data-text", "Get in touch");
			attr(span4, "class", "btn-area");
			attr(a5, "class", "nav-link btn btn-sm btn-primary btn-sm-rounded svelte-10pddvj");
			attr(a5, "href", "contact");
			attr(li4, "class", "nav-item svelte-10pddvj");
			attr(ul, "class", "navbar-nav ml-auto main-nav");
			attr(div0, "class", "collapse navbar-collapse");
			attr(div0, "id", "sitenavbar");
			attr(div1, "class", "container");
			attr(nav, "class", "navbar navbar-expand-lg site-navigation svelte-10pddvj");
		},
		m(target, anchor) {
			insert(target, nav, anchor);
			append(nav, div1);
			append(div1, a0);
			append(a0, img);
			append(div1, t0);
			append(div1, button);
			append(button, span0);
			append(button, t1);
			append(button, span1);
			append(button, t2);
			append(button, span2);
			append(div1, t3);
			append(div1, div0);
			append(div0, ul);
			append(ul, li0);
			append(li0, a1);
			append(a1, t4);
			append(ul, t5);
			append(ul, li1);
			append(li1, a2);
			append(a2, t6);
			append(ul, t7);
			append(ul, li2);
			append(li2, a3);
			append(a3, t8);
			append(ul, t9);
			append(ul, li3);
			append(li3, a4);
			append(a4, t10);
			append(ul, t11);
			append(ul, li4);
			append(li4, a5);
			append(a5, span4);
			append(span4, span3);
			append(span3, t12);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(nav);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;